<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use App\Models\Coupon;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create admin user
        User::create([
            'name' => 'Admin',
            'email' => 'admin@techdrop.com',
            'password' => Hash::make('password'),
            'email_verified_at' => now(),
        ]);

        // Create test customer
        User::create([
            'name' => 'John Doe',
            'email' => 'john@example.com',
            'password' => Hash::make('password'),
            'email_verified_at' => now(),
        ]);

        // Categories
        $categories = [
            ['name' => 'Smartphones & Accessories', 'slug' => 'smartphones', 'icon' => 'fas fa-mobile-alt', 'description' => 'Latest smartphones, cases, chargers & more', 'sort_order' => 1],
            ['name' => 'Smartwatches & Wearables', 'slug' => 'smartwatches', 'icon' => 'fas fa-clock', 'description' => 'Smart watches, fitness trackers & bands', 'sort_order' => 2],
            ['name' => 'Audio & Headphones', 'slug' => 'audio', 'icon' => 'fas fa-headphones-alt', 'description' => 'Wireless earbuds, headphones & speakers', 'sort_order' => 3],
            ['name' => 'Gaming Accessories', 'slug' => 'gaming', 'icon' => 'fas fa-gamepad', 'description' => 'Controllers, headsets & gaming gear', 'sort_order' => 4],
            ['name' => 'Smart Home', 'slug' => 'smart-home', 'icon' => 'fas fa-home', 'description' => 'Smart lights, cameras & IoT devices', 'sort_order' => 5],
            ['name' => 'Laptop & PC Accessories', 'slug' => 'laptop-accessories', 'icon' => 'fas fa-laptop', 'description' => 'Keyboards, mice, hubs & stands', 'sort_order' => 6],
        ];

        foreach ($categories as $cat) {
            Category::create($cat);
        }

        // Products
        $products = [
            // Smartphones & Accessories
            [
                'name' => 'MagSafe Wireless Charger Pro',
                'slug' => 'magsafe-wireless-charger-pro',
                'sku' => 'TD-WC-001',
                'short_description' => '15W Fast Wireless Charging Pad with LED Indicator',
                'description' => '<p>Experience the future of charging with our MagSafe Wireless Charger Pro. Featuring 15W fast charging capability, this sleek pad magnetically aligns with your phone for perfect positioning every time.</p><h4>Key Features</h4><ul><li>15W fast wireless charging</li><li>Magnetic alignment technology</li><li>LED charging indicator</li><li>Anti-slip silicone base</li><li>Universal Qi compatibility</li></ul>',
                'price' => 1299,
                'compare_price' => 2499,
                'cost_price' => 450,
                'category_id' => 1,
                'brand' => 'TechDrop',
                'image' => 'https://images.unsplash.com/photo-1615526675159-e248c3021d3f?w=600',
                'specifications' => json_encode(['Power' => '15W', 'Input' => 'USB-C', 'Compatibility' => 'Qi-enabled devices', 'Weight' => '85g']),
                'stock' => 150,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.5,
                'reviews_count' => 234,
                'sales_count' => 1205,
            ],
            [
                'name' => 'Ultra Slim Phone Case - Carbon Fiber',
                'slug' => 'ultra-slim-carbon-fiber-case',
                'sku' => 'TD-PC-002',
                'short_description' => 'Premium carbon fiber texture case with military-grade protection',
                'description' => '<p>Our Ultra Slim Carbon Fiber case combines style with substance. The real carbon fiber texture provides a premium look while the shock-absorbing TPU inner layer delivers military-grade drop protection.</p>',
                'price' => 599,
                'compare_price' => 1299,
                'cost_price' => 180,
                'category_id' => 1,
                'brand' => 'ArmorTech',
                'image' => 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600',
                'specifications' => json_encode(['Material' => 'Carbon Fiber + TPU', 'Protection' => 'Military Grade', 'Weight' => '28g']),
                'stock' => 500,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-5 days',
                'rating' => 4.3,
                'reviews_count' => 189,
                'sales_count' => 3401,
            ],
            [
                'name' => '100W GaN USB-C Charger',
                'slug' => '100w-gan-usb-c-charger',
                'sku' => 'TD-CH-003',
                'short_description' => 'Compact 100W GaN charger with 3 ports - charges laptop & phone simultaneously',
                'description' => '<p>The most powerful pocket-sized charger you will ever own. With GaN III technology, this 100W charger is 40% smaller than traditional chargers while delivering enough power to charge your laptop, phone, and tablet simultaneously.</p>',
                'price' => 2499,
                'compare_price' => 4999,
                'cost_price' => 850,
                'category_id' => 1,
                'brand' => 'PowerMax',
                'image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600',
                'specifications' => json_encode(['Power' => '100W Total', 'Ports' => '2x USB-C, 1x USB-A', 'Technology' => 'GaN III', 'Weight' => '155g']),
                'stock' => 200,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.7,
                'reviews_count' => 567,
                'sales_count' => 2890,
            ],
            // Smartwatches
            [
                'name' => 'FitPro Ultra Smartwatch',
                'slug' => 'fitpro-ultra-smartwatch',
                'sku' => 'TD-SW-004',
                'short_description' => 'AMOLED display, heart rate, SpO2, GPS - 7 day battery life',
                'description' => '<p>Meet your new fitness companion. The FitPro Ultra features a stunning 1.75" AMOLED display, advanced health monitoring including heart rate, SpO2, and sleep tracking, plus built-in GPS for accurate outdoor activity tracking.</p>',
                'price' => 3999,
                'compare_price' => 7999,
                'cost_price' => 1200,
                'category_id' => 2,
                'brand' => 'FitPro',
                'image' => 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600',
                'specifications' => json_encode(['Display' => '1.75" AMOLED', 'Battery' => '7 days', 'Sensors' => 'HR, SpO2, GPS', 'Water Resistance' => 'IP68']),
                'stock' => 100,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '5-10 days',
                'rating' => 4.4,
                'reviews_count' => 891,
                'sales_count' => 4521,
            ],
            [
                'name' => 'Titanium Smart Band Pro',
                'slug' => 'titanium-smart-band-pro',
                'sku' => 'TD-SB-005',
                'short_description' => 'Sleek fitness band with titanium body and 14-day battery',
                'description' => '<p>The Titanium Smart Band Pro packs serious tech into a minimal form factor. With a titanium alloy body, 0.96" AMOLED screen, and 14-day battery life, it is the perfect everyday fitness companion.</p>',
                'price' => 1999,
                'compare_price' => 3499,
                'cost_price' => 650,
                'category_id' => 2,
                'brand' => 'FitPro',
                'image' => 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600',
                'specifications' => json_encode(['Display' => '0.96" AMOLED', 'Battery' => '14 days', 'Material' => 'Titanium Alloy', 'Weight' => '22g']),
                'stock' => 300,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.2,
                'reviews_count' => 445,
                'sales_count' => 6712,
            ],
            // Audio
            [
                'name' => 'AirBuds Pro X - Active Noise Cancelling',
                'slug' => 'airbuds-pro-x-anc',
                'sku' => 'TD-AB-006',
                'short_description' => 'True wireless earbuds with hybrid ANC, 40dB noise reduction',
                'description' => '<p>Immerse yourself in pure sound with AirBuds Pro X. Featuring hybrid active noise cancellation that blocks up to 40dB of ambient noise, these earbuds deliver studio-quality audio with deep bass and crystal-clear highs.</p>',
                'price' => 2799,
                'compare_price' => 5999,
                'cost_price' => 900,
                'category_id' => 3,
                'brand' => 'SoundCore',
                'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=600',
                'specifications' => json_encode(['Driver' => '11mm Dynamic', 'ANC' => 'Hybrid -40dB', 'Battery' => '8h + 32h case', 'Codec' => 'AAC, SBC, LDAC']),
                'stock' => 250,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.6,
                'reviews_count' => 1023,
                'sales_count' => 8900,
            ],
            [
                'name' => 'BassBox 360 Portable Speaker',
                'slug' => 'bassbox-360-speaker',
                'sku' => 'TD-SP-007',
                'short_description' => '360° surround sound, waterproof, 24hr battery, RGB lights',
                'description' => '<p>Take the party anywhere with BassBox 360. This rugged portable speaker delivers immersive 360-degree surround sound with deep, punchy bass. With IPX7 waterproofing, 24-hour battery, and mesmerizing RGB light effects.</p>',
                'price' => 3499,
                'compare_price' => 6499,
                'cost_price' => 1100,
                'category_id' => 3,
                'brand' => 'SoundCore',
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600',
                'specifications' => json_encode(['Power' => '30W', 'Battery' => '24 hours', 'Waterproof' => 'IPX7', 'Connectivity' => 'BT 5.3, AUX']),
                'stock' => 120,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '5-10 days',
                'rating' => 4.4,
                'reviews_count' => 378,
                'sales_count' => 2100,
            ],
            [
                'name' => 'StudioMax Over-Ear Headphones',
                'slug' => 'studiomax-over-ear-headphones',
                'sku' => 'TD-HP-008',
                'short_description' => 'Hi-Res Audio, 60hr battery, foldable design, premium comfort',
                'description' => '<p>For audiophiles who demand the best. StudioMax over-ear headphones feature 50mm beryllium drivers, Hi-Res Audio certification, and adaptive noise cancellation. With 60 hours of battery life and ultra-soft memory foam cushions.</p>',
                'price' => 4999,
                'compare_price' => 8999,
                'cost_price' => 1600,
                'category_id' => 3,
                'brand' => 'StudioMax',
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
                'specifications' => json_encode(['Driver' => '50mm Beryllium', 'Battery' => '60 hours', 'ANC' => 'Adaptive', 'Certification' => 'Hi-Res Audio']),
                'stock' => 80,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '5-10 days',
                'rating' => 4.8,
                'reviews_count' => 612,
                'sales_count' => 3200,
            ],
            // Gaming
            [
                'name' => 'ProGamer RGB Mechanical Keyboard',
                'slug' => 'progamer-rgb-mechanical-keyboard',
                'sku' => 'TD-KB-009',
                'short_description' => 'Hot-swappable switches, per-key RGB, aircraft-grade aluminum',
                'description' => '<p>Dominate every game with the ProGamer RGB Mechanical Keyboard. Featuring hot-swappable mechanical switches, per-key RGB backlighting with 16.8 million colors, and an aircraft-grade aluminum frame built to withstand intense gaming sessions.</p>',
                'price' => 3299,
                'compare_price' => 5999,
                'cost_price' => 1050,
                'category_id' => 4,
                'brand' => 'ProGamer',
                'image' => 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600',
                'specifications' => json_encode(['Switch' => 'Hot-swappable', 'Backlight' => 'Per-key RGB', 'Frame' => 'Aluminum', 'Anti-ghosting' => 'N-Key Rollover']),
                'stock' => 150,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '5-10 days',
                'rating' => 4.6,
                'reviews_count' => 723,
                'sales_count' => 4100,
            ],
            [
                'name' => 'TurboX Gaming Mouse - 16000 DPI',
                'slug' => 'turbox-gaming-mouse',
                'sku' => 'TD-GM-010',
                'short_description' => '16000 DPI optical sensor, programmable buttons, lightweight 68g',
                'description' => '<p>Precision meets speed with the TurboX Gaming Mouse. Equipped with a 16000 DPI optical sensor, 7 programmable buttons, and an ultra-lightweight honeycomb design at just 68g — engineered for competitive esports.</p>',
                'price' => 1899,
                'compare_price' => 3499,
                'cost_price' => 600,
                'category_id' => 4,
                'brand' => 'TurboX',
                'image' => 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=600',
                'specifications' => json_encode(['Sensor' => '16000 DPI Optical', 'Buttons' => '7 Programmable', 'Weight' => '68g', 'Polling Rate' => '1000Hz']),
                'stock' => 200,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.5,
                'reviews_count' => 534,
                'sales_count' => 5600,
            ],
            [
                'name' => 'RGB Gaming Headset - Surround Sound',
                'slug' => 'rgb-gaming-headset-surround',
                'sku' => 'TD-GH-011',
                'short_description' => '7.1 virtual surround, detachable mic, memory foam cushions',
                'description' => '<p>Hear every footstep with crystal clarity. This RGB Gaming Headset features 7.1 virtual surround sound, a noise-cancelling detachable microphone, and ultra-comfortable memory foam ear cushions for marathon gaming sessions.</p>',
                'price' => 2299,
                'compare_price' => 4499,
                'cost_price' => 750,
                'category_id' => 4,
                'brand' => 'ProGamer',
                'image' => 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600',
                'specifications' => json_encode(['Audio' => '7.1 Virtual Surround', 'Driver' => '50mm', 'Mic' => 'Detachable Noise-Cancelling', 'Cushion' => 'Memory Foam']),
                'stock' => 170,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '5-10 days',
                'rating' => 4.3,
                'reviews_count' => 312,
                'sales_count' => 2800,
            ],
            // Smart Home
            [
                'name' => 'SmartCam 360 - AI Security Camera',
                'slug' => 'smartcam-360-ai-camera',
                'sku' => 'TD-SC-012',
                'short_description' => '2K resolution, 360° rotation, AI person detection, night vision',
                'description' => '<p>Keep your home safe with SmartCam 360. This AI-powered security camera features 2K resolution, 360-degree rotation, intelligent person detection, and full-color night vision. Get instant alerts on your phone when motion is detected.</p>',
                'price' => 2999,
                'compare_price' => 5499,
                'cost_price' => 950,
                'category_id' => 5,
                'brand' => 'HomeSafe',
                'image' => 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600',
                'specifications' => json_encode(['Resolution' => '2K QHD', 'Rotation' => '360°', 'AI' => 'Person Detection', 'Night Vision' => 'Full Color']),
                'stock' => 130,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '5-10 days',
                'rating' => 4.5,
                'reviews_count' => 456,
                'sales_count' => 3400,
            ],
            [
                'name' => 'Smart LED Strip Light - 10M RGB',
                'slug' => 'smart-led-strip-10m-rgb',
                'sku' => 'TD-SL-013',
                'short_description' => 'WiFi + Alexa/Google, 16M colors, music sync, app control',
                'description' => '<p>Transform your space with our 10-meter Smart LED Strip Lights. With 16 million colors, music sync mode, and app/voice control via Alexa or Google Home, create the perfect ambiance for any mood.</p>',
                'price' => 1499,
                'compare_price' => 2999,
                'cost_price' => 480,
                'category_id' => 5,
                'brand' => 'LumiHome',
                'image' => 'https://images.unsplash.com/photo-1615796153287-98eacf0abb13?w=600',
                'specifications' => json_encode(['Length' => '10 meters', 'Colors' => '16M RGB', 'Control' => 'WiFi, App, Voice', 'Compatible' => 'Alexa, Google Home']),
                'stock' => 400,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.3,
                'reviews_count' => 678,
                'sales_count' => 9200,
            ],
            // Laptop & PC
            [
                'name' => 'USB-C Docking Station 12-in-1',
                'slug' => 'usb-c-docking-station-12in1',
                'sku' => 'TD-DS-014',
                'short_description' => 'Triple display, 100W PD, ethernet, SD card, USB 3.0 hub',
                'description' => '<p>Transform your laptop into a full workstation with our 12-in-1 USB-C Docking Station. Supports triple displays (dual HDMI + VGA), 100W Power Delivery pass-through charging, Gigabit Ethernet, and more.</p>',
                'price' => 3999,
                'compare_price' => 6999,
                'cost_price' => 1300,
                'category_id' => 6,
                'brand' => 'HubMax',
                'image' => 'https://images.unsplash.com/photo-1625842268584-8f3296236571?w=600',
                'specifications' => json_encode(['Ports' => '12-in-1', 'Display' => 'Triple (2x HDMI + VGA)', 'PD' => '100W', 'Ethernet' => 'Gigabit']),
                'stock' => 90,
                'is_active' => true,
                'is_featured' => true,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '5-10 days',
                'rating' => 4.6,
                'reviews_count' => 234,
                'sales_count' => 1800,
            ],
            [
                'name' => 'Ergonomic Laptop Stand - Aluminum',
                'slug' => 'ergonomic-laptop-stand-aluminum',
                'sku' => 'TD-LS-015',
                'short_description' => 'Adjustable height, heat dissipation, fits 10-17" laptops',
                'description' => '<p>Elevate your workspace ergonomics with our premium aluminum laptop stand. Six adjustable height settings, built-in heat dissipation design, and anti-slip silicone pads keep your laptop secure and cool.</p>',
                'price' => 1799,
                'compare_price' => 3499,
                'cost_price' => 550,
                'category_id' => 6,
                'brand' => 'ErgoDesk',
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600',
                'specifications' => json_encode(['Material' => 'Aluminum Alloy', 'Compatibility' => '10-17" Laptops', 'Height' => '6 Adjustable Settings', 'Weight Capacity' => '15kg']),
                'stock' => 350,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.4,
                'reviews_count' => 345,
                'sales_count' => 4500,
            ],
            [
                'name' => 'Wireless Mechanical Numpad',
                'slug' => 'wireless-mechanical-numpad',
                'sku' => 'TD-NP-016',
                'short_description' => 'Bluetooth + 2.4G, mechanical switches, backlit, rechargeable',
                'description' => '<p>The perfect companion for your laptop. This wireless mechanical numpad features dual connectivity (Bluetooth + 2.4G), tactile mechanical switches, customizable RGB backlighting, and a built-in rechargeable battery.</p>',
                'price' => 1299,
                'compare_price' => 2499,
                'cost_price' => 400,
                'category_id' => 6,
                'brand' => 'KeyTech',
                'image' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600',
                'specifications' => json_encode(['Switch' => 'Mechanical', 'Connectivity' => 'BT 5.0 + 2.4G', 'Battery' => '1000mAh Rechargeable', 'Backlight' => 'RGB']),
                'stock' => 220,
                'is_active' => true,
                'is_featured' => false,
                'supplier_name' => 'CJ Dropshipping',
                'shipping_time' => '3-7 days',
                'rating' => 4.1,
                'reviews_count' => 156,
                'sales_count' => 2300,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        // Coupons
        Coupon::create([
            'code' => 'WELCOME10',
            'type' => 'percentage',
            'value' => 10,
            'min_order' => 999,
            'max_uses' => 1000,
            'expires_at' => now()->addMonths(3),
            'is_active' => true,
        ]);

        Coupon::create([
            'code' => 'TECH500',
            'type' => 'fixed',
            'value' => 500,
            'min_order' => 2999,
            'max_uses' => 500,
            'expires_at' => now()->addMonths(1),
            'is_active' => true,
        ]);
    }
}
